### ISSUE TITLE
ER Diagram

### ISSUE THREAD

**Issue by satayyeb** [AlieNiT/course-gpt#1]
نمودار ER برای نشون دادن ارتباط مدل هامون باید تهیه بشه تا مدل رو از روی نمودار بزنیم. سایت زیر برای کشیدن ERD خوبه:

https://app.diagrams.net/

**Comment by AlieNiT** [comment]
https://drive.google.com/file/d/1BusakIW3h3FndjaxOa5l3_lG_O7A563A/view?usp=sharing
